=== focus-shift/jollyday/jollyday-core/src/main/resources/focus_shift.de/jollyday/schema/holiday/holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://focus_shift.de/jollyday/schema/holiday"
            xmlns="https://focus_shift.de/jollyday/schema/holiday"
            elementFormDefault="qualified">

  <xsd:simpleType name="Weekday">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MONDAY"/>
      <xsd:enumeration value="TUESDAY"/>
      <xsd:enumeration value="WEDNESDAY"/>
      <xsd:enumeration value="THURSDAY"/>
      <xsd:enumeration value="FRIDAY"/>
      <xsd:enumeration value="SATURDAY"/>
      <xsd:enumeration value="SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Month">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JANUARY"/>
      <xsd:enumeration value="FEBRUARY"/>
      <xsd:enumeration value="MARCH"/>
      <xsd:enumeration value="APRIL"/>
      <xsd:enumeration value="MAY"/>
      <xsd:enumeration value="JUNE"/>
      <xsd:enumeration value="JULY"/>
      <xsd:enumeration value="AUGUST"/>
      <xsd:enumeration value="SEPTEMBER"/>
      <xsd:enumeration value="OCTOBER"/>
      <xsd:enumeration value="NOVEMBER"/>
      <xsd:enumeration value="DECEMBER"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="Days" type="xsd:int" minOccurs="0"/>
            <xsd:element name="Weekday" type="Weekday" minOccurs="0"/>
          </xsd:choice>
          <xsd:element name="When" type="When"/>
          <xsd:element name="Date" type="Fixed"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holidays">
    <xsd:sequence>
      <xsd:element name="Fixed" type="Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToFixed" type="RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToWeekdayInMonth" type="RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="ChristianHoliday" type="ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="IslamicHoliday" type="IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayBetweenFixed" type="FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayRelativeToFixed" type="FixedWeekdayRelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="EthiopianOrthodoxHoliday" type="EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToEasterSunday" type="RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="Configuration" type="Configuration"/>

  <xsd:complexType name="Configuration">
    <xsd:sequence>
      <xsd:element name="Holidays" type="Holidays"/>
      <xsd:element name="Sources" type="Sources" minOccurs="0"/>
      <xsd:element name="SubConfigurations" type="Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="hierarchy" type="xsd:string"/>
    <xsd:attribute name="description" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="Source">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="of" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Sources">
    <xsd:sequence>
      <xsd:element name="Source" type="Source" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Fixed">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="month" type="Month"/>
        <xsd:attribute name="day">
          <xsd:simpleType>
            <xsd:restriction base="xsd:int">
              <xsd:minInclusive value="1"/>
              <xsd:maxInclusive value="31"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="When">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="BEFORE"/>
      <xsd:enumeration value="AFTER"/>
      <xsd:enumeration value="CLOSEST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="month" type="Month"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="Which">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="FIRST"/>
      <xsd:enumeration value="SECOND"/>
      <xsd:enumeration value="THIRD"/>
      <xsd:enumeration value="FOURTH"/>
      <xsd:enumeration value="LAST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="IslamicHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="IslamicHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="IslamicHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEWYEAR"/>
      <xsd:enumeration value="ASCHURA"/>
      <xsd:enumeration value="MAWLID_AN_NABI"/>
      <xsd:enumeration value="LAILAT_AL_MIRAJ"/>
      <xsd:enumeration value="LAILAT_AL_BARAT"/>
      <xsd:enumeration value="RAMADAN"/>
      <xsd:enumeration value="JUMUATUL_WIDA"/>
      <xsd:enumeration value="LAILAT_AL_QADR"/>
      <xsd:enumeration value="RAMADAN_END"/>
      <xsd:enumeration value="ID_AL_FITR"/>
      <xsd:enumeration value="ID_AL_FITR_2"/>
      <xsd:enumeration value="ID_AL_FITR_3"/>
      <xsd:enumeration value="ARAFAAT"/>
      <xsd:enumeration value="ID_UL_ADHA"/>
      <xsd:enumeration value="ID_UL_ADHA_2"/>
      <xsd:enumeration value="ID_UL_ADHA_3"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChronologyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JULIAN"/>
      <xsd:enumeration value="GREGORIAN"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="ChristianHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="ChristianHolidayType"/>
        <xsd:attribute name="chronology" type="ChronologyType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="PUBLIC_HOLIDAY"/>
      <xsd:enumeration value="BANK_HOLIDAY"/>
      <xsd:enumeration value="OBSERVANCE"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChristianHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="GOOD_FRIDAY"/>
      <xsd:enumeration value="EASTER_MONDAY"/>
      <xsd:enumeration value="ASCENSION_DAY"/>
      <xsd:enumeration value="WHIT_MONDAY"/>
      <xsd:enumeration value="CORPUS_CHRISTI"/>
      <xsd:enumeration value="PALM_SUNDAY"/>
      <xsd:enumeration value="MAUNDY_THURSDAY"/>
      <xsd:enumeration value="ASH_WEDNESDAY"/>
      <xsd:enumeration value="MARDI_GRAS"/>
      <xsd:enumeration value="GENERAL_PRAYER_DAY"/>
      <xsd:enumeration value="CLEAN_MONDAY"/>
      <xsd:enumeration value="SHROVE_MONDAY"/>
      <xsd:enumeration value="PENTECOST"/>
      <xsd:enumeration value="CARNIVAL"/>
      <xsd:enumeration value="EASTER_SATURDAY"/>
      <xsd:enumeration value="EASTER_TUESDAY"/>
      <xsd:enumeration value="SACRED_HEART"/>
      <xsd:enumeration value="EASTER"/>
      <xsd:enumeration value="PENTECOST_MONDAY"/>
      <xsd:enumeration value="WHIT_SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayBetweenFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="from" type="Fixed"/>
          <xsd:element name="to" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holiday" abstract="true">
    <xsd:attribute name="validFrom" type="xsd:int"/>
    <xsd:attribute name="validTo" type="xsd:int"/>
    <xsd:attribute name="every" type="HolidayCycleType" default="EVERY_YEAR"/>
    <xsd:attribute name="descriptionPropertiesKey" type="xsd:string"/>
    <xsd:attribute name="localizedType" type="HolidayType" default="PUBLIC_HOLIDAY"/>
  </xsd:complexType>

  <xsd:simpleType name="Substituted">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ON_SATURDAY"/>
      <xsd:enumeration value="ON_SUNDAY"/>
      <xsd:enumeration value="ON_WEEKEND"/>
      <xsd:enumeration value="ON_TUESDAY"/>
      <xsd:enumeration value="ON_WEDNESDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="With">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEXT"/>
      <xsd:enumeration value="PREVIOUS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="MovingCondition">
    <xsd:attribute name="substitute" type="Weekday"/>
    <xsd:attribute name="with" type="With"/>
    <xsd:attribute name="weekday" type="Weekday"/>
  </xsd:complexType>

  <xsd:complexType name="MoveableHoliday" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="MovingCondition" type="MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="EthiopianOrthodoxHoliday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:attribute name="type" type="EthiopianOrthodoxHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="EthiopianOrthodoxHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TIMKAT"/>
      <xsd:enumeration value="ENKUTATASH"/>
      <xsd:enumeration value="MESKEL"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayRelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="day" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayCycleType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="EVERY_YEAR"/>
      <xsd:enumeration value="TWO_YEARS"/>
      <xsd:enumeration value="THREE_YEARS"/>
      <xsd:enumeration value="FOUR_YEARS"/>
      <xsd:enumeration value="FIVE_YEARS"/>
      <xsd:enumeration value="SIX_YEARS"/>
      <xsd:enumeration value="ODD_YEARS"/>
      <xsd:enumeration value="EVEN_YEARS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToEasterSunday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="chronology" type="ChronologyType"/>
          <xsd:element name="days" type="xsd:int"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_be.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="be" description="Belgium"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JULY" day="21" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS" localizedType="OBSERVANCE"/>
    <Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="ARMISTICE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="KINGS_FEAST" localizedType="OBSERVANCE" />
    <Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE" localizedType="OBSERVANCE"/>
    <ChristianHoliday type="EASTER"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
    <ChristianHoliday type="PENTECOST"/>
    <ChristianHoliday type="PENTECOST_MONDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Belgium</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:BE</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:BE</Source>
  </Sources>

</Configuration>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_sg_2017.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="sg" description="Singapore"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="28" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="JANUARY" day="30" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="APRIL" day="14" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="10" descriptionPropertiesKey="VESAK_DAY"/>
    <Fixed month="JUNE" day="26" descriptionPropertiesKey="HARI_RAYA_PUASA"/>
    <Fixed month="AUGUST" day="9" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="SEPTEMBER" day="1" descriptionPropertiesKey="HARI_RAYA_HAJI"/>
    <Fixed month="OCTOBER" day="18" descriptionPropertiesKey="DEEPAVALI"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>
</Configuration>

=== focus-shift/jollyday/jollyday-test/src/test/resources/holidays/Holidays_test_ua_2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ua" description="Ukraine"
                   xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
    <tns:Holidays>
        <tns:Fixed month="JANUARY" day="1"/>
        <tns:Fixed month="JANUARY" day="7"/>
        <tns:Fixed month="MARCH" day="9"/>
        <tns:Fixed month="APRIL" day="13"/>
        <tns:Fixed month="MAY" day="1"/>
        <tns:Fixed month="MAY" day="4"/>
        <tns:Fixed month="MAY" day="11"/>
        <tns:Fixed month="JUNE" day="1"/>
        <tns:Fixed month="JUNE" day="29"/>
        <tns:Fixed month="AUGUST" day="24"/>
        <tns:Fixed month="OCTOBER" day="14"/>
    </tns:Holidays>
</tns:Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_kw.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="kw" description="Kuwait"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="25" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="FEBRUARY" day="26" descriptionPropertiesKey="LIBERATION_DAY"/>
    <IslamicHoliday type="NEWYEAR"/>
    <IslamicHoliday type="MAWLID_AN_NABI"/>
    <IslamicHoliday type="LAILAT_AL_MIRAJ"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_AL_FITR_2"/>
    <IslamicHoliday type="ID_AL_FITR_3"/>
    <IslamicHoliday type="ARAFAAT"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
    <IslamicHoliday type="ID_UL_ADHA_2"/>
    <IslamicHoliday type="ID_UL_ADHA_3"/>
  </Holidays>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_kn.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="kn" description="Saint Kitts and Nevis"
                xmlns="https://focus_shift.de/jollyday/schema/holiday"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="CARNIVAL_DAY"/>

    <Fixed month="JANUARY" day="28" descriptionPropertiesKey="BUCKLYS_UPRISING_DAY"/>

    <Fixed month="SEPTEMBER" day="16" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>

    <Fixed month="SEPTEMBER" day="19" descriptionPropertiesKey="INDEPENDENCE_DAY"/>

    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS">
      <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="TUESDAY"/>
    </Fixed>

    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>

    <FixedWeekday which="FIRST" weekday="MONDAY" month="MAY" descriptionPropertiesKey="LABOUR_DAY"/>
    <FixedWeekday which="FIRST" weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="EMANCIPATION_DAY"/>
    <FixedWeekday which="FIRST" weekday="TUESDAY" month="AUGUST" descriptionPropertiesKey="CULTURAMA_DAY"/>

    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="WHIT_MONDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Saint_Kitts_and_Nevis</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:KN</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:KN</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_hk_2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="hk" description="Hong Kong"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="FIRST_DAY_OF_JANUARY"/>
    <Fixed month="FEBRUARY" day="16" descriptionPropertiesKey="LUNAR_NEW_YEARS_DAY"/>
    <Fixed month="FEBRUARY" day="17" descriptionPropertiesKey="SECOND_DAY_OF_LUNAR_NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="19" descriptionPropertiesKey="THIRD_DAY_OF_LUNAR_NEW_YEAR"/>
    <Fixed month="MARCH" day="30" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MARCH" day="31" descriptionPropertiesKey="DAY_FOLLOWING_GOOD_FRIDAY"/>
    <Fixed month="APRIL" day="2" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="APRIL" day="5" descriptionPropertiesKey="CHING_MING_FESTIVAL"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="22" descriptionPropertiesKey="BIRTHDAY_OF_THE_BUDDHA"/>
    <Fixed month="JUNE" day="18" descriptionPropertiesKey="TUEN_NG_FESTIVAL"/>
    <Fixed month="JULY" day="2" descriptionPropertiesKey="HONG_KONG_SPECIAL_REGION"/>
    <Fixed month="SEPTEMBER" day="25" descriptionPropertiesKey="DAY_FOLLOWING_CHINESE_MID_AUTUMN"/>
    <Fixed month="OCTOBER" day="1" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="OCTOBER" day="17" descriptionPropertiesKey="CHUNG_YEUNG_FESTIVAL"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="FIRST_WEEKDAY_AFTER_CHRISTMAS"/>
  </Holidays>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_om.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="om" description="Oman"
                xmlns="https://focus_shift.de/jollyday/schema/holiday"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="11" descriptionPropertiesKey="ACCESSION_DAY"/>
    <Fixed month="JULY" day="23" descriptionPropertiesKey="RENAISSANCE_DAY"/>
    <Fixed month="OCTOBER" day="17" descriptionPropertiesKey="WOMENS_DAY"/>
    <Fixed month="NOVEMBER" day="20" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="NOVEMBER" day="21" descriptionPropertiesKey="NATIONAL_DAY"/>
    <IslamicHoliday type="NEWYEAR"/>
    <IslamicHoliday type="MAWLID_AN_NABI"/>
    <IslamicHoliday type="LAILAT_AL_MIRAJ"/>
    <IslamicHoliday type="RAMADAN_END"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_AL_FITR_2"/>
    <IslamicHoliday type="ID_AL_FITR_3"/>
    <IslamicHoliday type="ARAFAAT"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
    <IslamicHoliday type="ID_UL_ADHA_2"/>
    <IslamicHoliday type="ID_UL_ADHA_3"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Oman</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:OM</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:OM</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_mu_2024.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="mu" description="Mauritius"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="10" descriptionPropertiesKey="CHINESE_SPRING_FESTIVAL"/>
    <Fixed month="FEBRUARY" day="1" descriptionPropertiesKey="ABOLITION_OF_SLAVERY"/>
    <Fixed month="JANUARY" day="25" descriptionPropertiesKey="THAIPOOSAM_CAVEDEE"/>
    <Fixed month="MARCH" day="8" descriptionPropertiesKey="MAHA_SHIVRATREE"/>
    <Fixed month="MARCH" day="12" descriptionPropertiesKey="INDEPENDENCE_AND_REPUBLIC_DAY"/>
    <Fixed month="APRIL" day="9" descriptionPropertiesKey="UGAADI"/>
    <Fixed month="APRIL" day="10" descriptionPropertiesKey="islamic.ID_AL_FITR"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_BLESSED_VIRGIN_MARY"/>
    <Fixed month="SEPTEMBER" day="8" descriptionPropertiesKey="GANESH_CHATURTHI"/>
    <Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ARRIVAL_OF_INDENTURED_LABORERS"/>
    <Fixed month="OCTOBER" day="31" descriptionPropertiesKey="DIVALI"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>

  <Sources>
    <Source>https://pmo.govmu.org/Communique/Notice%20-%20Final%20Public%20holidays%20-%202024.pdf</Source>
  </Sources>
</Configuration>
