=== focus-shift/jollyday/jollyday-core/src/main/resources/focus_shift.de/jollyday/schema/holiday/holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://focus_shift.de/jollyday/schema/holiday"
            xmlns="https://focus_shift.de/jollyday/schema/holiday"
            elementFormDefault="qualified">

  <xsd:simpleType name="Weekday">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MONDAY"/>
      <xsd:enumeration value="TUESDAY"/>
      <xsd:enumeration value="WEDNESDAY"/>
      <xsd:enumeration value="THURSDAY"/>
      <xsd:enumeration value="FRIDAY"/>
      <xsd:enumeration value="SATURDAY"/>
      <xsd:enumeration value="SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Month">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JANUARY"/>
      <xsd:enumeration value="FEBRUARY"/>
      <xsd:enumeration value="MARCH"/>
      <xsd:enumeration value="APRIL"/>
      <xsd:enumeration value="MAY"/>
      <xsd:enumeration value="JUNE"/>
      <xsd:enumeration value="JULY"/>
      <xsd:enumeration value="AUGUST"/>
      <xsd:enumeration value="SEPTEMBER"/>
      <xsd:enumeration value="OCTOBER"/>
      <xsd:enumeration value="NOVEMBER"/>
      <xsd:enumeration value="DECEMBER"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="Days" type="xsd:int" minOccurs="0"/>
            <xsd:element name="Weekday" type="Weekday" minOccurs="0"/>
          </xsd:choice>
          <xsd:element name="When" type="When"/>
          <xsd:element name="Date" type="Fixed"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holidays">
    <xsd:sequence>
      <xsd:element name="Fixed" type="Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToFixed" type="RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToWeekdayInMonth" type="RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="ChristianHoliday" type="ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="IslamicHoliday" type="IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayBetweenFixed" type="FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayRelativeToFixed" type="FixedWeekdayRelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="EthiopianOrthodoxHoliday" type="EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToEasterSunday" type="RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="Configuration" type="Configuration"/>

  <xsd:complexType name="Configuration">
    <xsd:sequence>
      <xsd:element name="Holidays" type="Holidays"/>
      <xsd:element name="Sources" type="Sources" minOccurs="0"/>
      <xsd:element name="SubConfigurations" type="Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="hierarchy" type="xsd:string"/>
    <xsd:attribute name="description" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="Source">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="of" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Sources">
    <xsd:sequence>
      <xsd:element name="Source" type="Source" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Fixed">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="month" type="Month"/>
        <xsd:attribute name="day">
          <xsd:simpleType>
            <xsd:restriction base="xsd:int">
              <xsd:minInclusive value="1"/>
              <xsd:maxInclusive value="31"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="When">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="BEFORE"/>
      <xsd:enumeration value="AFTER"/>
      <xsd:enumeration value="CLOSEST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="month" type="Month"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="Which">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="FIRST"/>
      <xsd:enumeration value="SECOND"/>
      <xsd:enumeration value="THIRD"/>
      <xsd:enumeration value="FOURTH"/>
      <xsd:enumeration value="LAST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="IslamicHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="IslamicHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="IslamicHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEWYEAR"/>
      <xsd:enumeration value="ASCHURA"/>
      <xsd:enumeration value="MAWLID_AN_NABI"/>
      <xsd:enumeration value="LAILAT_AL_MIRAJ"/>
      <xsd:enumeration value="LAILAT_AL_BARAT"/>
      <xsd:enumeration value="RAMADAN"/>
      <xsd:enumeration value="JUMUATUL_WIDA"/>
      <xsd:enumeration value="LAILAT_AL_QADR"/>
      <xsd:enumeration value="RAMADAN_END"/>
      <xsd:enumeration value="ID_AL_FITR"/>
      <xsd:enumeration value="ID_AL_FITR_2"/>
      <xsd:enumeration value="ID_AL_FITR_3"/>
      <xsd:enumeration value="ARAFAAT"/>
      <xsd:enumeration value="ID_UL_ADHA"/>
      <xsd:enumeration value="ID_UL_ADHA_2"/>
      <xsd:enumeration value="ID_UL_ADHA_3"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChronologyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JULIAN"/>
      <xsd:enumeration value="GREGORIAN"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="ChristianHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="ChristianHolidayType"/>
        <xsd:attribute name="chronology" type="ChronologyType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="PUBLIC_HOLIDAY"/>
      <xsd:enumeration value="BANK_HOLIDAY"/>
      <xsd:enumeration value="OBSERVANCE"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChristianHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="GOOD_FRIDAY"/>
      <xsd:enumeration value="EASTER_MONDAY"/>
      <xsd:enumeration value="ASCENSION_DAY"/>
      <xsd:enumeration value="WHIT_MONDAY"/>
      <xsd:enumeration value="CORPUS_CHRISTI"/>
      <xsd:enumeration value="PALM_SUNDAY"/>
      <xsd:enumeration value="MAUNDY_THURSDAY"/>
      <xsd:enumeration value="ASH_WEDNESDAY"/>
      <xsd:enumeration value="MARDI_GRAS"/>
      <xsd:enumeration value="GENERAL_PRAYER_DAY"/>
      <xsd:enumeration value="CLEAN_MONDAY"/>
      <xsd:enumeration value="SHROVE_MONDAY"/>
      <xsd:enumeration value="PENTECOST"/>
      <xsd:enumeration value="CARNIVAL"/>
      <xsd:enumeration value="EASTER_SATURDAY"/>
      <xsd:enumeration value="EASTER_TUESDAY"/>
      <xsd:enumeration value="SACRED_HEART"/>
      <xsd:enumeration value="EASTER"/>
      <xsd:enumeration value="PENTECOST_MONDAY"/>
      <xsd:enumeration value="WHIT_SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayBetweenFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="from" type="Fixed"/>
          <xsd:element name="to" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holiday" abstract="true">
    <xsd:attribute name="validFrom" type="xsd:int"/>
    <xsd:attribute name="validTo" type="xsd:int"/>
    <xsd:attribute name="every" type="HolidayCycleType" default="EVERY_YEAR"/>
    <xsd:attribute name="descriptionPropertiesKey" type="xsd:string"/>
    <xsd:attribute name="localizedType" type="HolidayType" default="PUBLIC_HOLIDAY"/>
  </xsd:complexType>

  <xsd:simpleType name="Substituted">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ON_SATURDAY"/>
      <xsd:enumeration value="ON_SUNDAY"/>
      <xsd:enumeration value="ON_WEEKEND"/>
      <xsd:enumeration value="ON_TUESDAY"/>
      <xsd:enumeration value="ON_WEDNESDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="With">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEXT"/>
      <xsd:enumeration value="PREVIOUS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="MovingCondition">
    <xsd:attribute name="substitute" type="Weekday"/>
    <xsd:attribute name="with" type="With"/>
    <xsd:attribute name="weekday" type="Weekday"/>
  </xsd:complexType>

  <xsd:complexType name="MoveableHoliday" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="MovingCondition" type="MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="EthiopianOrthodoxHoliday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:attribute name="type" type="EthiopianOrthodoxHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="EthiopianOrthodoxHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TIMKAT"/>
      <xsd:enumeration value="ENKUTATASH"/>
      <xsd:enumeration value="MESKEL"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayRelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="day" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayCycleType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="EVERY_YEAR"/>
      <xsd:enumeration value="TWO_YEARS"/>
      <xsd:enumeration value="THREE_YEARS"/>
      <xsd:enumeration value="FOUR_YEARS"/>
      <xsd:enumeration value="FIVE_YEARS"/>
      <xsd:enumeration value="SIX_YEARS"/>
      <xsd:enumeration value="ODD_YEARS"/>
      <xsd:enumeration value="EVEN_YEARS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToEasterSunday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="chronology" type="ChronologyType"/>
          <xsd:element name="days" type="xsd:int"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_sg_2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="sg" description="Singapore"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="12" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="13" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="APRIL" day="2" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="13" descriptionPropertiesKey="HARI_RAYA_PUASA"/>
    <Fixed month="MAY" day="26" descriptionPropertiesKey="VESAK_DAY"/>
    <Fixed month="JULY" day="20" descriptionPropertiesKey="HARI_RAYA_HAJI"/>
    <Fixed month="AUGUST" day="9" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="NOVEMBER" day="4" descriptionPropertiesKey="DEEPAVALI"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_cf.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="cf" description="Central African Republic"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="29" descriptionPropertiesKey="BOGANDA"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JUNE" day="30" descriptionPropertiesKey="christian.GENERAL_PRAYER_DAY"/>
    <Fixed month="AUGUST" day="13" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="1" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
    <ChristianHoliday type="WHIT_MONDAY"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Central_African_Republic</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:CF</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:CF</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_sx.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="sx" description="Sint Maarten"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <!-- Landsverordening houdende berekening van termijnen (P.B. 2001, no. 27), Art. 3, as
         currently in force: eleven statutory items (one covering both Christmas days), none of
         which include Easter Sunday or Whit Sunday/Monday - those appear on aggregator sites
         but not in the actual ordinance text. -->
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>

    <!-- "de dag waarop de verjaardag van de Koning officieel wordt gevierd" - Dutch royal
         tradition: if 27 April falls on a Sunday, King's Day moves BACKWARD to the preceding
         Saturday (confirmed for 2025: 27 April was a Sunday, observed Saturday 26 April). -->
    <Fixed month="APRIL" day="27" descriptionPropertiesKey="KINGS_DAY">
      <MovingCondition substitute="SUNDAY" with="PREVIOUS" weekday="SATURDAY"/>
    </Fixed>

    <!-- "de datum vallende na de gehouden Carnavalsoptocht" - statutorily the day after the
         Carnival parade (ministerially designated each year), but consistently observed on 30
         April in practice for every year checked. -->
    <Fixed month="APRIL" day="30" descriptionPropertiesKey="CARNIVAL_DAY"/>

    <!-- "de dag van de arbeid (1 mei) ... indien deze op zondag valt, dan wordt deze gevierd op
         de eerstvolgende werkdag" - if Sunday, observed the following Monday. -->
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- "de Dag van de Bevrijding, dan wel Emancipation Day" - commemorates the abolition of
         slavery on 1 July 1863; if it falls on a Sunday it is observed the following Monday. -->
    <Fixed month="JULY" day="1" descriptionPropertiesKey="EMANCIPATION_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="ST_MARTIN"/>

    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="SECOND_CHRISTMAS_DAY"/>

    <!-- "de dag van de Constitutie, dan wel Constitution Day" - commemorates Sint Maarten
         becoming an autonomous country within the Kingdom of the Netherlands on 10 October 2010. -->
    <FixedWeekday which="SECOND" weekday="MONDAY" month="OCTOBER" descriptionPropertiesKey="CONSTITUTION_DAY"/>

    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Sint_Maarten</Source>
    <Source of="Landsverordening houdende berekening van termijnen, Art. 3 (consolidated, in force since 2015-10-04)">https://lokaleregelgeving.overheid.nl/CVDR142304</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:SX</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:SX</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_sn.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="sn" description="Senegal"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="APRIL" day="4" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>

    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
    <ChristianHoliday type="WHIT_MONDAY"/>

    <IslamicHoliday type="NEWYEAR"/>
    <IslamicHoliday type="ASCHURA"/>
    <IslamicHoliday type="MAWLID_AN_NABI"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
    <IslamicHoliday type="GRAND_MAGAL_OF_TOUBA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Senegal</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:SN</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:SN</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_vg_2023.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="vg" description="Virgin Islands (British)"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="6" descriptionPropertiesKey="STOUTTS_BIRTHDAY"/>
    <Fixed month="APRIL" day="7" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="APRIL" day="10" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="8" descriptionPropertiesKey="KINGS_CORONATION"/>
    <Fixed month="MAY" day="29" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
    <Fixed month="JUNE" day="16" descriptionPropertiesKey="SOVEREIGNS_BIRTHDAY"/>
    <Fixed month="JULY" day="3" descriptionPropertiesKey="VIRGIN_ISLANDS_DAY"/>
    <Fixed month="AUGUST" day="7" descriptionPropertiesKey="EMANCIPATION_MONDAY"/>
    <Fixed month="AUGUST" day="8" descriptionPropertiesKey="EMANCIPATION_TUESDAY"/>
    <Fixed month="AUGUST" day="9" descriptionPropertiesKey="EMANCIPATION_WEDNESDAY"/>
    <Fixed month="OCTOBER" day="16" descriptionPropertiesKey="HEROES_AND_FOREPARENTS_DAY"/>
    <Fixed month="NOVEMBER" day="27" descriptionPropertiesKey="1949_GREAT_MARCH_AND_RESTORATION"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>

  <Sources>
    <Source>https://bvi.gov.vg/media-centre/june-16-public-holiday-lieu-june-9</Source>
    <Source>https://bvi.gov.vg/media-centre/may-8-and-june-16-declared-public-holidays</Source>
    <Source>https://bvi.gov.vg/media-centre/monday-may-8-public-holiday</Source>
    <Source>https://bvi.gov.vg/media-centre/updatedofficialholidays20231</Source>
    <Source>https://bvi.gov.vg/media-centre/cabinet-approves-2023-public-holidays</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_pl.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="pl" description="Poland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="3" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="DECEMBER" day="24" validFrom="2025" descriptionPropertiesKey="CHRISTMAS_EVE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <ChristianHoliday type="EASTER"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="PENTECOST"/>
    <ChristianHoliday type="CORPUS_CHRISTI"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Poland</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:PL</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:PL</Source>
  </Sources>

</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_lb.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="lb" description="Lebanon"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">

  <Holidays>
    <!-- Fixed date national holidays -->
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="FEBRUARY" day="9" descriptionPropertiesKey="SAINT_MARONS"/>
    <Fixed month="FEBRUARY" day="14" descriptionPropertiesKey="HARIRI_MEMORIAL_DAY"/>
    <Fixed month="MARCH" day="25" descriptionPropertiesKey="ANNUNCIATION"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="25" descriptionPropertiesKey="RESISTANCE_LIBERATION_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="22" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>

    <!-- Moveable Christian holidays (Gregorian/Western chronology) -->
    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER"/>

    <!-- Islamic holidays (lunar calendar driven) -->
    <IslamicHoliday type="NEWYEAR"/>
    <IslamicHoliday type="ASCHURA"/>
    <IslamicHoliday type="MAWLID_AN_NABI"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Lebanon</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_gh.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="gh" description="Ghana"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="JANUARY" day="7" descriptionPropertiesKey="CONSTITUTION_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="MARCH" day="6" descriptionPropertiesKey="INDEPENDENCE_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="JULY" day="1" descriptionPropertiesKey="REPUBLIC_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="SEPTEMBER" day="21" descriptionPropertiesKey="FOUNDERS_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY">
      <MovingCondition substitute="MONDAY" with="NEXT" weekday="TUESDAY"/>
    </Fixed>

    <FixedWeekday which="FIRST" weekday="FRIDAY" month="DECEMBER" descriptionPropertiesKey="FARMERS_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </FixedWeekday>

    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY"/>

    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Ghana</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:GH</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:GH</Source>
  </Sources>
</Configuration>
