=== focus-shift/jollyday/jollyday-core/src/main/resources/focus_shift.de/jollyday/schema/holiday/holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://focus_shift.de/jollyday/schema/holiday"
            xmlns="https://focus_shift.de/jollyday/schema/holiday"
            elementFormDefault="qualified">

  <xsd:simpleType name="Weekday">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MONDAY"/>
      <xsd:enumeration value="TUESDAY"/>
      <xsd:enumeration value="WEDNESDAY"/>
      <xsd:enumeration value="THURSDAY"/>
      <xsd:enumeration value="FRIDAY"/>
      <xsd:enumeration value="SATURDAY"/>
      <xsd:enumeration value="SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Month">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JANUARY"/>
      <xsd:enumeration value="FEBRUARY"/>
      <xsd:enumeration value="MARCH"/>
      <xsd:enumeration value="APRIL"/>
      <xsd:enumeration value="MAY"/>
      <xsd:enumeration value="JUNE"/>
      <xsd:enumeration value="JULY"/>
      <xsd:enumeration value="AUGUST"/>
      <xsd:enumeration value="SEPTEMBER"/>
      <xsd:enumeration value="OCTOBER"/>
      <xsd:enumeration value="NOVEMBER"/>
      <xsd:enumeration value="DECEMBER"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="Days" type="xsd:int" minOccurs="0"/>
            <xsd:element name="Weekday" type="Weekday" minOccurs="0"/>
          </xsd:choice>
          <xsd:element name="When" type="When"/>
          <xsd:element name="Date" type="Fixed"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holidays">
    <xsd:sequence>
      <xsd:element name="Fixed" type="Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToFixed" type="RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToWeekdayInMonth" type="RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="ChristianHoliday" type="ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="IslamicHoliday" type="IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayBetweenFixed" type="FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayRelativeToFixed" type="FixedWeekdayRelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="EthiopianOrthodoxHoliday" type="EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToEasterSunday" type="RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="Configuration" type="Configuration"/>

  <xsd:complexType name="Configuration">
    <xsd:sequence>
      <xsd:element name="Holidays" type="Holidays"/>
      <xsd:element name="Sources" type="Sources" minOccurs="0"/>
      <xsd:element name="SubConfigurations" type="Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="hierarchy" type="xsd:string"/>
    <xsd:attribute name="description" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="Source">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="of" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Sources">
    <xsd:sequence>
      <xsd:element name="Source" type="Source" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Fixed">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="month" type="Month"/>
        <xsd:attribute name="day">
          <xsd:simpleType>
            <xsd:restriction base="xsd:int">
              <xsd:minInclusive value="1"/>
              <xsd:maxInclusive value="31"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="When">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="BEFORE"/>
      <xsd:enumeration value="AFTER"/>
      <xsd:enumeration value="CLOSEST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="month" type="Month"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="Which">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="FIRST"/>
      <xsd:enumeration value="SECOND"/>
      <xsd:enumeration value="THIRD"/>
      <xsd:enumeration value="FOURTH"/>
      <xsd:enumeration value="LAST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="IslamicHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="IslamicHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="IslamicHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEWYEAR"/>
      <xsd:enumeration value="ASCHURA"/>
      <xsd:enumeration value="MAWLID_AN_NABI"/>
      <xsd:enumeration value="LAILAT_AL_MIRAJ"/>
      <xsd:enumeration value="LAILAT_AL_BARAT"/>
      <xsd:enumeration value="RAMADAN"/>
      <xsd:enumeration value="JUMUATUL_WIDA"/>
      <xsd:enumeration value="LAILAT_AL_QADR"/>
      <xsd:enumeration value="RAMADAN_END"/>
      <xsd:enumeration value="ID_AL_FITR"/>
      <xsd:enumeration value="ID_AL_FITR_2"/>
      <xsd:enumeration value="ID_AL_FITR_3"/>
      <xsd:enumeration value="ARAFAAT"/>
      <xsd:enumeration value="ID_UL_ADHA"/>
      <xsd:enumeration value="ID_UL_ADHA_2"/>
      <xsd:enumeration value="ID_UL_ADHA_3"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChronologyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JULIAN"/>
      <xsd:enumeration value="GREGORIAN"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="ChristianHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="ChristianHolidayType"/>
        <xsd:attribute name="chronology" type="ChronologyType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="PUBLIC_HOLIDAY"/>
      <xsd:enumeration value="BANK_HOLIDAY"/>
      <xsd:enumeration value="OBSERVANCE"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChristianHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="GOOD_FRIDAY"/>
      <xsd:enumeration value="EASTER_MONDAY"/>
      <xsd:enumeration value="ASCENSION_DAY"/>
      <xsd:enumeration value="WHIT_MONDAY"/>
      <xsd:enumeration value="CORPUS_CHRISTI"/>
      <xsd:enumeration value="PALM_SUNDAY"/>
      <xsd:enumeration value="MAUNDY_THURSDAY"/>
      <xsd:enumeration value="ASH_WEDNESDAY"/>
      <xsd:enumeration value="MARDI_GRAS"/>
      <xsd:enumeration value="GENERAL_PRAYER_DAY"/>
      <xsd:enumeration value="CLEAN_MONDAY"/>
      <xsd:enumeration value="SHROVE_MONDAY"/>
      <xsd:enumeration value="PENTECOST"/>
      <xsd:enumeration value="CARNIVAL"/>
      <xsd:enumeration value="EASTER_SATURDAY"/>
      <xsd:enumeration value="EASTER_TUESDAY"/>
      <xsd:enumeration value="SACRED_HEART"/>
      <xsd:enumeration value="EASTER"/>
      <xsd:enumeration value="PENTECOST_MONDAY"/>
      <xsd:enumeration value="WHIT_SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayBetweenFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="from" type="Fixed"/>
          <xsd:element name="to" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holiday" abstract="true">
    <xsd:attribute name="validFrom" type="xsd:int"/>
    <xsd:attribute name="validTo" type="xsd:int"/>
    <xsd:attribute name="every" type="HolidayCycleType" default="EVERY_YEAR"/>
    <xsd:attribute name="descriptionPropertiesKey" type="xsd:string"/>
    <xsd:attribute name="localizedType" type="HolidayType" default="PUBLIC_HOLIDAY"/>
  </xsd:complexType>

  <xsd:simpleType name="Substituted">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ON_SATURDAY"/>
      <xsd:enumeration value="ON_SUNDAY"/>
      <xsd:enumeration value="ON_WEEKEND"/>
      <xsd:enumeration value="ON_TUESDAY"/>
      <xsd:enumeration value="ON_WEDNESDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="With">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEXT"/>
      <xsd:enumeration value="PREVIOUS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="MovingCondition">
    <xsd:attribute name="substitute" type="Weekday"/>
    <xsd:attribute name="with" type="With"/>
    <xsd:attribute name="weekday" type="Weekday"/>
  </xsd:complexType>

  <xsd:complexType name="MoveableHoliday" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="MovingCondition" type="MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="EthiopianOrthodoxHoliday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:attribute name="type" type="EthiopianOrthodoxHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="EthiopianOrthodoxHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TIMKAT"/>
      <xsd:enumeration value="ENKUTATASH"/>
      <xsd:enumeration value="MESKEL"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayRelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="day" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayCycleType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="EVERY_YEAR"/>
      <xsd:enumeration value="TWO_YEARS"/>
      <xsd:enumeration value="THREE_YEARS"/>
      <xsd:enumeration value="FOUR_YEARS"/>
      <xsd:enumeration value="FIVE_YEARS"/>
      <xsd:enumeration value="SIX_YEARS"/>
      <xsd:enumeration value="ODD_YEARS"/>
      <xsd:enumeration value="EVEN_YEARS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToEasterSunday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="chronology" type="ChronologyType"/>
          <xsd:element name="days" type="xsd:int"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_na.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="na" description="Namibia"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <!-- New Year's Day -->
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Independence Day -->
    <Fixed month="MARCH" day="21" descriptionPropertiesKey="INDEPENDENCE_DAY" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Workers' Day -->
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Cassinga Day -->
    <Fixed month="MAY" day="4" descriptionPropertiesKey="CASSINGA" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Africa Day -->
    <Fixed month="MAY" day="25" descriptionPropertiesKey="AFRICA_DAY" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Genocide Remembrance Day -->
    <Fixed month="MAY" day="28" descriptionPropertiesKey="GENOCIDE_REMEMBRANCE" validFrom="2016">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Heroes' Day -->
    <Fixed month="AUGUST" day="26" descriptionPropertiesKey="HEROES" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Human Rights Day -->
    <Fixed month="DECEMBER" day="10" descriptionPropertiesKey="HUMAN_RIGHTS" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Christmas Day -->
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Family Day -->
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="FAMILY_DAY" validFrom="1990">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <!-- Good Friday -->
    <ChristianHoliday type="GOOD_FRIDAY"/>

    <!-- Easter Monday -->
    <ChristianHoliday type="EASTER_MONDAY"/>

    <!-- Ascension Day -->
    <ChristianHoliday type="ASCENSION_DAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Namibia</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:NA</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:NA</Source>
  </Sources>

</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_vc.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="vc" description="Saint Vincent and the Grenadines"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="14" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="AUGUST" day="1" descriptionPropertiesKey="EMANCIPATION_DAY"/>
    <Fixed month="OCTOBER" day="27" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>

    <FixedWeekday which="FIRST" weekday="MONDAY" month="JULY" descriptionPropertiesKey="CARNIVAL_MONDAY"/>
    <FixedWeekday which="FIRST" weekday="TUESDAY" month="JULY" descriptionPropertiesKey="CARNIVAL_TUESDAY"/>

    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="WHIT_MONDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Saint_Vincent_and_the_Grenadines</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:VC</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:VC</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_tg.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="tg" description="Togo"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="13" descriptionPropertiesKey="LIBERATION_DAY"/>
    <Fixed month="APRIL" day="27" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JUNE" day="21" descriptionPropertiesKey="MARTYRS_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
    <ChristianHoliday type="WHIT_MONDAY"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Togo</Source>
    <Source of="ISO 3166-1">https://en.wikipedia.org/wiki/ISO_3166-1:TG</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:TG</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:TG</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_cd.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="cd" description="Democratic Republic of the Congo"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="4" descriptionPropertiesKey="MARTYRS_DAY"/>
    <Fixed month="JANUARY" day="16" descriptionPropertiesKey="LAURENT_DESIRE_KABILA_ASSASSINATION"/>
    <Fixed month="JANUARY" day="17" descriptionPropertiesKey="PATRICE_LUMUMBA_ASSASSINATION"/>
    <Fixed month="APRIL" day="6" descriptionPropertiesKey="KIMBANGUS_DAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="17" validTo="2018" descriptionPropertiesKey="LIBERATION"/>
    <Fixed month="MAY" day="17" validFrom="2019" descriptionPropertiesKey="ARMED_FORCES_DAY"/>
    <Fixed month="JUNE" day="30" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="AUGUST" day="1" descriptionPropertiesKey="PARENTS_DAY"/>
    <Fixed month="AUGUST" day="2" descriptionPropertiesKey="CONGOLESE_GENOCIDE_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_the_Democratic_Republic_of_the_Congo</Source>
    <Source>https://www.officeholidays.com/countries/dr-congo</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:CD</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:CD</Source>
  </Sources>

  <SubConfigurations hierarchy="BU" description="Lower Uele">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="EQ" description="Equator">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="HK" description="Upper Katanga">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="HL" description="Upper Lomami">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="HU" description="Upper Uele">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="IT" description="Ituri">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KS" description="Kasai">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KC" description="Central Kasai">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KE" description="Eastern Kasai">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KN" description="Kinshasa">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="BC" description="Central Kongo">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KG" description="Kwango">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="KL" description="Kwilu">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="LO" description="Lomami">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="LU" description="Lualaba">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="MN" description="Mai-Ndombe">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="MA" description="Maniema">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="MO" description="Mongala">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="NK" description="North Kivu">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="NU" description="North Ubangi">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="SA" description="Sankuru">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="SK" description="South Kivu">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="SU" description="South Ubangi">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="TA" description="Tanganyika">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="TO" description="Tshopo">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="TU" description="Tshuapa">
    <Holidays/>
  </SubConfigurations>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_va.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="va" description="Vatican City State"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="SOLEMNITY_MARY_MOTHER"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="FEBRUARY" day="11" descriptionPropertiesKey="FOUNDATION_ANNIVERSARY"/>
    <Fixed month="MARCH" day="13" validFrom="2014" validTo="2025" descriptionPropertiesKey="PETER_FRANCIS_ELECTION"/>
    <Fixed month="MARCH" day="19" descriptionPropertiesKey="ST_JOSEPH"/>
    <Fixed month="APRIL" day="23" descriptionPropertiesKey="ST_GEORGE"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="ST_JOSEPH_WORKER"/>
    <Fixed month="MAY" day="8" validFrom="2026" descriptionPropertiesKey="LEO_XIV_ELECTION"/>
    <Fixed month="JUNE" day="29" descriptionPropertiesKey="ST_PETER_PAUL"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_MARY"/>
    <Fixed month="NOVEMBER" day="17" descriptionPropertiesKey="ST_ROBERT_BELLARMINE"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="8" descriptionPropertiesKey="IMMACULATE_CONCEPTION"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Vatican_City</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:VA</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:VA</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_pe.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="pe" description="Peru"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JUNE" day="29" descriptionPropertiesKey="ST_PETER_PAUL"/>
    <Fixed month="JULY" day="28" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="JULY" day="29" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="AUGUST" day="30" descriptionPropertiesKey="SANTA_ROSA"/>
    <Fixed month="OCTOBER" day="8" descriptionPropertiesKey="ANGAMOS"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="8" descriptionPropertiesKey="IMMACULATE_CONCEPTION"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="EASTER"/>
    <ChristianHoliday type="MAUNDY_THURSDAY"/>
    <ChristianHoliday type="GOOD_FRIDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Peru</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:PE</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:PE</Source>
  </Sources>

</Configuration>
